name: 'banvic_dbt'
version: '1.0.0'
config-version: 2


profile: 'banvic'

vars:
  start_date: '2010-02-01'
  end_date: '2023-02-01'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  banvic_dbt:
    +materialized: ephemeral
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  banvic_dbt:
    exchange_rate:
      +schema: exchange_rate_raw
    banvic:
      +schema: banvic_raw
